const assert=require('node:assert/strict');
const fs=require('node:fs');
const {find}=require('../web/school-address-search.js');
const rows=[{street:'AYACUCHO',alias:'Ayacucho',ranges:[[1601,1699],[1602,1700]],block:'a'}, {street:'9 DE JULIO AV.',alias:'AV. 9 DE JULIO',ranges:[[1,99],[2,100]],block:null}];
assert.equal(find(rows,'Ayacucho 1670').matches[0].block,'a');
assert.equal(find(rows,'Av. 9 de Julio 50').matches[0].block,null);
assert.ok(find(rows,'Ayacucho').error);
assert.ok(find(rows,'Inventada 123').error);
assert.ok(find(rows,'Ayacucho 5000').error);
const data=JSON.parse(fs.readFileSync('data/processed/school-streets.json','utf8'));
const index=JSON.parse(fs.readFileSync('data/processed/school-addresses.json','utf8'));
assert.ok(find(index,'Ayacucho 1670').matches.some(r=>r.block));
const {select,summarize}=require('../web/school-filters.js');
const selected=select(data,{review:true,minimum:1});
const stats=summarize(selected,data.schools);
assert.ok(stats.area>2000000&&stats.area<2100000);
assert.equal(stats.measuredBlocks,1703);
const matchIds=new Set(find(index,'Ayacucho 1670').matches.map(r=>r.block));
assert.ok(selected.some(f=>matchIds.has(f.properties.id)));
assert.equal(select(data,{review:true,minimum:100}).filter(f=>matchIds.has(f.properties.id)).length,0);
console.log('Búsqueda, selección y superficie real: OK',stats.area);
